#!/usr/bin/env bash
#
# This file must be used with "source <file path>" *from bash*.
# You cannot run it directly.

# Determine if the script is being sourced or executed.
if [[ "${BASH_SOURCE[0]}" = "${0}" ]]; then
	echo "This file must be sourced."
	exit 1
fi

# Python virtualenv.
FILEPATH_0="./venv/bin/activate"
FILEPATH_1="./venv/Scripts/activate"

if [ -e "${FILEPATH_0}" ]; then
	source ${FILEPATH_0}
elif [ -e "${FILEPATH_1}" ]; then
	source ${FILEPATH_1}
else
	echo "Nothing to source. Try to do $ python -m venv venv"
	exit 1
fi

# Python IO encoding for the terminal.
export PYTHONIOENCODING=utf-8
